theme: minima
title: Transformation de Fourier
author: SHI
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: pretty